# Generated by Django 2.1.2 on 2019-02-25 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_auto_20190225_2347'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='gray_photo',
            new_name='output',
        ),
    ]
