# Generated by Django 2.1.2 on 2019-02-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='gray_photo',
            field=models.ImageField(default='defo', upload_to='gray_documents/'),
        ),
    ]
