# Generated by Django 2.1.2 on 2019-02-25 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_document_gray_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gray',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gray_photo', models.ImageField(default='gray_documents/gray.jpg', upload_to='gray_documents/')),
            ],
        ),
        migrations.RemoveField(
            model_name='document',
            name='gray_photo',
        ),
    ]
