# Generated by Django 2.1.2 on 2019-02-25 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_auto_20190225_1408'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gray',
        ),
        migrations.AddField(
            model_name='document',
            name='gray_photo',
            field=models.ImageField(default='gray_documents/gray.jpg', upload_to='gray_documents/'),
        ),
    ]
